In [2]:
import numpy as np

In [10]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [12]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr5=np.random.rand(4,2)
arr5

array([[0.31911808, 0.29882945],
       [0.51392925, 0.89048705],
       [0.33410207, 0.56601449],
       [0.90890308, 0.34387165]])

Slicing

In [21]:
print(arr1[:-1])

[1 2 3 4]


In [23]:
print(arr2[0:2,2:4])

[[3 4]
 [4 5]]


In [24]:
print(arr2[1,2])

4


In [25]:
a=5
print(arr1+a)

[ 6  7  8  9 10]


In [27]:
print(arr4-arr3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
print(arr2/2)

[[0.5 1.  1.5 2.  2.5]
 [1.  1.5 2.  2.5 3. ]]


In [30]:
arr6=np.arange(1,10000)
arr6

array([   1,    2,    3, ..., 9997, 9998, 9999])

In [32]:
result=[]
for x in arr6:
  result.append(x*2)

print(result)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10), np.int64(12), np.int64(14), np.int64(16), np.int64(18), np.int64(20), np.int64(22), np.int64(24), np.int64(26), np.int64(28), np.int64(30), np.int64(32), np.int64(34), np.int64(36), np.int64(38), np.int64(40), np.int64(42), np.int64(44), np.int64(46), np.int64(48), np.int64(50), np.int64(52), np.int64(54), np.int64(56), np.int64(58), np.int64(60), np.int64(62), np.int64(64), np.int64(66), np.int64(68), np.int64(70), np.int64(72), np.int64(74), np.int64(76), np.int64(78), np.int64(80), np.int64(82), np.int64(84), np.int64(86), np.int64(88), np.int64(90), np.int64(92), np.int64(94), np.int64(96), np.int64(98), np.int64(100), np.int64(102), np.int64(104), np.int64(106), np.int64(108), np.int64(110), np.int64(112), np.int64(114), np.int64(116), np.int64(118), np.int64(120), np.int64(122), np.int64(124), np.int64(126), np.int64(128), np.int64(130), np.int64(132), np.int64(134), np.int64(136), np.int64(138), np.int64(140), np

In [33]:
result=arr6*2

In [35]:
def normalize(x):
  return (x-np.min(x))/(np.min(x)-np.max(x))

In [36]:
print(arr1)

[1 2 3 4 5]


In [38]:
normalize(arr1)

array([-0.  , -0.25, -0.5 , -0.75, -1.  ])

In [40]:
def euclidean(a,b):
  return np.sqrt(np.sum((a-b)**2))
euclidean(4,6)

np.float64(2.0)

In [41]:
def mean_vectorized(x):
  return np.sum(x)/len(x)

In [42]:
mean_vectorized(arr4)

np.float64(3.0)

In [57]:
arr7=np.array([[1,2,3,4,5,6],[2,3,4,5,3,5],[2,3,4,5,3,5]])
arr7

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 3, 5],
       [2, 3, 4, 5, 3, 5]])

In [58]:
normalixe(arr7)

array([[-0. , -0.2, -0.4, -0.6, -0.8, -1. ],
       [-0.2, -0.4, -0.6, -0.8, -0.4, -0.8],
       [-0.2, -0.4, -0.6, -0.8, -0.4, -0.8]])